baseURL = "/"
languageCode = "en-us"
title = "Favorite Quotes"
ignoreFiles = ["_drafts$"]
paginate = 1000000
theme = "binario"

[Params]
  copyright = "Garrett Hyde"

[Params.Entry]
  meta = ["date"]
